@startuml

MonoBehaviour <|-- GameController
MonoBehaviour <|-- BlockSet
MonoBehaviour <|-- Block
MonoBehaviour <|-- Field
MonoBehaviour <|-- StatusPanel
MonoBehaviour <|-- InputManager

MonoBehaviour <|-- StateGameBoot
MonoBehaviour <|-- StateGameMain
MonoBehaviour <|-- StateGameFinish
@enduml