@startuml

UnityEngine.MonoBehaviour <|-- GameController
UnityEngine.MonoBehaviour <|-- BlockSet
UnityEngine.MonoBehaviour <|-- Block
UnityEngine.MonoBehaviour <|-- Field
UnityEngine.MonoBehaviour <|-- StatusPanel
UnityEngine.MonoBehaviour <|-- InputManager
UnityEngine.MonoBehaviour <|-- AbstractField

UnityEngine.MonoBehaviour <|-- StateGameBoot
UnityEngine.MonoBehaviour <|-- StateGameMain
UnityEngine.MonoBehaviour <|-- StateGameFinish
@enduml