@startuml

UnityEngine.MonoBehaviour <|-- AbstractField
UnityEngine.MonoBehaviour <|-- AbstractBlockSet
UnityEngine.MonoBehaviour <|-- AbstractStateGameMain

UnityEngine.MonoBehaviour <|-- GameController
UnityEngine.MonoBehaviour <|-- Block
UnityEngine.MonoBehaviour <|-- StatusPanel
UnityEngine.MonoBehaviour <|-- InputManager

UnityEngine.MonoBehaviour <|-- StateGameBoot
UnityEngine.MonoBehaviour <|-- StateGameMain
UnityEngine.MonoBehaviour <|-- StateGameFinish
UnityEngine.MonoBehaviour <|-- ReservationList
@enduml