@startuml

class Block
{
    + Px : int
    + Py : int
}

' フィールドの状態を管理する
abstract class AbstractField
{
    + ResetField(sound : ISoundManager, width: int, height: int, borderLine : int) : void[]
    + Width() : int
    ' @return ブロックが積みあがってしまったらtrue, そうでなければfalse を返す
    + SetBlocks(blocks : Block[]) : bool

    + IsHit(blocks : Vector2Int[]) : bool
}

class Field
{
    - _width : int
    - _height : int
    - _borderLine : int
    - _soundPlaces : UnityEngine.AudioSource
    ..
    - _activeParts : Block[,]
    - _sound : ISoundManager

    --
    + ResetField(sound : ISoundManager, width: int, height: int, borderLine : int) : void[]
    + Width() : int
    ' @return ブロックが積みあがってしまったらtrue, そうでなければfalse を返す
    + SetBlocks(blocks : Block[]) : bool

    + IsHit(blocks : Vector2Int[]) : bool
    + RefTransform() : Transform
}

' ゲームの進行を管理する
class GameController
{
    - _players : Player[]
    - _fieldPrefab: AbstractField
    - _blockSetPrefabOptions : AbstractBlockSet[]
    - _sound : UnitySoundManager
    - _boot : StateGameBoot
    - _main : AbstStateGameMain
    - _finish : StateGameFinish
    - _fallLevel: int
    ..
    --

    - Start() : void

    + BootGame() : void
    + RunGame() : void
    + FinishGame() : void
}

interface IPlayer
{
    + Setup(fieldPrefab: AbstractField, blockSetPrefabOptions : AbstractBlockSet[], sound : ISoundManager, fallLevel: int) : void
    + StartGame(parent : AbstractStateGameMain) : void
    + IsAlive() : bool
    + Dead() : void
    + PullNextBlock() : void
}


class Player
{
    - _input : InputManager
    - _soundCollide : UnityEngine.AudioSource
    ..
    - _parent : AbstractStateGameMain
    - _field : AbstractField
    - _blockSetPrefabOptions : AbstractBlockSet[]
    - _sound : ISoundManager
    - _alive : bool
    - _currentBlock : AbstractBlockSet
    - _fallLevel: int
    --

    - FixedUpdate() : void

    + Setup(fieldPrefab: AbstractField, blockSetPrefabOptions : AbstractBlockSet[], sound : ISoundManager, fallLevel: int) : void
    + StartGame(parent : AbstractStateGameMain) : void
    + IsAlive() : bool
    + Dead() : void
    + PullNextBlock() : void
}

class StateGameBoot
{
    - _countMax : int
    - _counter : UnityEngine.UI.Text
    ..
    - _parent : GameController
    --

    + Setup(fieldPrefab: AbstractField, parent : GameController, player : Player[], blockSetPrefabOptions : AbstractBlockSet[], sound : ISoundManager, fallLevel: int) : void
    - CoRun() : IEnumerator
}

abstract class AbstractStateGameMain
{
    + Setup(parent : GameController, players : Player[]) : void
    + PlayerGameOver(player : Player) : void
}

class StateGameMain
{
    - _parent : GameController
    - _players : IPlayer[]

    - GetNumberOfAlivingPlayer() : int

    + Setup(parent : GameController, players : Player[]) : void
    + PlayerGameOver(player : Player) : void
}

class StateGameFinish
{
    - _waitMax : float
    - _message : UnityEngine.UI.Text
    ..
    - _parent : GameController
    --

    + Setup(parent : GameController) : void
    - CoRun() : IEnumerator
}

interface IInputManager
{
    + IsRotateRight() : bool
    + IsRotateLeft() : bool
    + IsMoveRight() : bool
    + IsMoveLeft() : bool
    + IsMoveDown) : bool
}

abstract class InputManager
{
    + {abstract} IsRotateRight() : bool
    + {abstract} IsRotateLeft() : bool
    + {abstract} IsMoveRight() : bool
    + {abstract} IsMoveLeft() : bool
    + {abstract} IsMoveDown) : bool
}

class UnityKeyInputManager
{
    + IsRotateRight() : bool
    + IsRotateLeft() : bool
    + IsMoveRight() : bool
    + IsMoveLeft() : bool
    + IsMoveDown() : bool
}

abstract class AbstractBlockSet
{
    + Setup(owner: IPlayer, filed: IField, input: IInputManager, sound: ISoundManager, fallLevel: int) : void
}

' ブロックの状態を管理する
class BlockSet
{
    - _soundCollide : UnityEngine.AudioSource
    - _prefabPart : Block
    - _partsPositions : Vector2Int[]
    ..
    - _activeBlocks : Block[]
    - _falling : bool
    - _field : IField
    - _owner : IPlayer
    - _input : IInputManager
    - _sound : ISoundManager
    - _rotStep : int
    - _centerPos : Vector2Int
    - _countWaitFalling : int
    - _countFalling : int
    - {const} CountWaitFallingLimit : int
    + {readonly} CountFallingLimit : int
    --

    - FixedUpdate() : void
    - UpdateInput() : void
    - RotateRight() : void
    - RotateLeft() : void
    - Rotate(dir : int) : void
    - ToBlocks() : Vector2Int[]
    - RotatePart(p : Vector2Int) : Vector2Int
    ' @return 移動できる場合はtrue, 何かにぶつかって移動できない場合はfalse
    - MoveRight() : bool
    ' @return 移動できる場合はtrue, 何かにぶつかって移動できない場合はfalse
    - MoveLeft() : bool
    - MoveDown() : void
    - Move() : void
    - ShowBlocks() : void
    - NeedToFall() : bool

    + Setup(owner: IPlayer, filed: IField, input: IInputManager, sound: ISoundManager, fallLevel: int) : void
    + CenterPos() : Vector2Int
}

interface ISoundManager
{
    + Play(sound : AudioSource) : void
    + Stop(sound : AudioSource) : void
}

class UnitySoundManager
{
    + Play(sound : AudioSource) : void
    + Stop(sound : AudioSource) : void
}

class StatusPanel
{
    - _scoreText : Text
 
    + ResetScore() : void
    + AddScore(addedScore : int) : void
}

Player "1" *-- "1" AbstractField
Player "1" o-- "0, 1" AbstractBlockSet
Player "1" o-- "1..*" AbstractBlockSet
Player "1" *-- "1" InputManager
Player "1" o-- "1" ISoundManager

GameController "1" *-- "1..*" Player
GameController "1" *-- "1..*" BlockSet
GameController "1" *-- "1" StateGameBoot
GameController "1" *-- "1" StateGameMain
GameController "1" *-- "1" StateGameFinish
GameController "1" *-- "1" UnitySoundManager

StateGameMain "1" o--o "*" IPlayer

StatusPanel "1" --o "1" GameController

IInputManager <|.. InputManager
InputManager <|.. UnityKeyInputManager
ISoundManager <|.. UnitySoundManager
AbstractBlockSet <|.. BlockSet
AbstractField <|.. Field
AbstractStateGameMain <|.. StateGameMain
IPlayer <|.. Player

Field "1" o-- "*" Block
BlockSet "1" o-- "*" Block
BlockSet "1" o-- "1" ISoundManager
BlockSet "1" o-- "1" IPlayer
BlockSet "1" o-- "1" AbstractField

@enduml