@startuml

[-> BlockSet : FixedUpdate
activate BlockSet
    BlockSet -> BlockSet : UpdateInput
        activate BlockSet
        deactivate BlockSet
    BlockSet -> BlockSet : Move
        activate BlockSet
        deactivate BlockSet
    BlockSet -> BlockSet : ShowBlocks
        activate BlockSet
        deactivate BlockSet
deactivate BlockSet


[-> BlockSet : UpdateInput
activate BlockSet
    BlockSet -> InuptManager : IsRotateRight
    activate InuptManager
        BlockSet <-- InuptManager
    deactivate InuptManager
    opt 右回転キーが押された
        BlockSet -> BlockSet : RotateRight
        activate BlockSet
        deactivate BlockSet
    end
    BlockSet -> InuptManager : IsRotateLeft
    activate InuptManager
        BlockSet <-- InuptManager
    deactivate InuptManager
    opt 左回転キーが押された
        BlockSet -> BlockSet : RotateLeft
        activate BlockSet
        deactivate BlockSet
    end
    BlockSet -> InuptManager : IsMoveRight
    activate InuptManager
        BlockSet <-- InuptManager
    deactivate InuptManager
    opt 右移動キーが押された
        BlockSet -> BlockSet : MoveRight
        activate BlockSet
        deactivate BlockSet
    end
    BlockSet -> InuptManager : IsMoveLeft
    activate InuptManager
        BlockSet <-- InuptManager
    deactivate InuptManager
    opt 左移動キーが押された
        BlockSet -> BlockSet : MoveLeft
        activate BlockSet
        deactivate BlockSet
    end
    BlockSet -> InuptManager : IsMoveDown
    activate InuptManager
        BlockSet <-- InuptManager
    deactivate InuptManager
    opt 下移動キーが押された
        BlockSet -> BlockSet : MoveDown
        activate BlockSet
        deactivate BlockSet
    end

deactivate BlockSet
[<-- BlockSet

[-> BlockSet : RotateRight
activate BlockSet
    BlockSet -> BlockSet : Rotate(-1)
        activate BlockSet
        deactivate BlockSet
    [<-- BlockSet
deactivate BlockSet

[-> BlockSet : RotateLeft
activate BlockSet
    BlockSet -> BlockSet : Rotate(1)
        activate BlockSet
        deactivate BlockSet
    [<-- BlockSet
deactivate BlockSet

[-> BlockSet : Rotate
activate BlockSet
    loop 4回まで回転させる
        loop 原点位置を少しずつずらす
            BlockSet -> BlockSet : ToBlocks
            activate BlockSet
            deactivate BlockSet
            BlockSet -> Field : IsHit
            activate Field
            deactivate Field
            opt 位置をずらし、回転させてフィールド上のブロックに衝突していない
                [<-- BlockSet
            end
        end
    end
    [<-- BlockSet
deactivate BlockSet

[-> BlockSet : ToBlocks
activate BlockSet
    BlockSet -> BlockSet : RotatePart
    activate BlockSet
    deactivate BlockSet
    [<-- BlockSet
deactivate BlockSet

[-> BlockSet : MoveLeft
activate BlockSet
    BlockSet -> BlockSet : 左に移動させる
    activate BlockSet
    deactivate BlockSet
    BlockSet -> Field : IsHit
    activate Field
    deactivate Field
    alt フィールド上の設置済みブロック又は外壁にぶつかった
        BlockSet -> BlockSet : ブロックの位置を元に戻す
        activate BlockSet
        deactivate BlockSet
        BlockSet -> ISoundManager : Play
        activate ISoundManager
            BlockSet <-- ISoundManager
        deactivate ISoundManager

    [<-- BlockSet
    else
        BlockSet -> BlockSet : 移動の音を鳴らす
            activate BlockSet
            deactivate BlockSet
    [<-- BlockSet
    end
deactivate BlockSet


[-> BlockSet : MoveRight
activate BlockSet
    BlockSet -> BlockSet : 右に移動させる
    activate BlockSet
    deactivate BlockSet
    BlockSet -> Field : IsHit
    activate Field
    deactivate Field
    alt フィールド上の設置済みブロック又は外壁にぶつかった
        BlockSet -> BlockSet : ブロックの位置を元に戻す
        activate BlockSet
        deactivate BlockSet
        BlockSet -> ISoundManager : Play
        activate ISoundManager
            BlockSet <-- ISoundManager
        deactivate ISoundManager

    [<-- BlockSet
    else
        BlockSet -> BlockSet : 移動の音を鳴らす
            activate BlockSet
            deactivate BlockSet
    [<-- BlockSet
    end
deactivate BlockSet


[-> BlockSet : MoveDown
activate BlockSet
    BlockSet -> BlockSet : 落下中フラグ(_falling)をONにする
        activate BlockSet
        deactivate BlockSet
    [<-- BlockSet
deactivate BlockSet


[-> BlockSet : Move
activate BlockSet
    BlockSet -> BlockSet : NeedToFall
    activate BlockSet
    deactivate BlockSet
    opt ブロックを下に移動させるタイミングに到達していない
        [<-- BlockSet
    end
    BlockSet -> BlockSet : ブロックを下に移動させる
    activate BlockSet
    deactivate BlockSet
    BlockSet -> Field : IsHit
    activate Field
    deactivate Field
    opt 接地した
        BlockSet -> BlockSet : ブロックの位置を元に戻す
        activate BlockSet
        deactivate BlockSet
        BlockSet -> BlockSet : ToBlocks
        activate BlockSet
        deactivate BlockSet
        loop 移動中のブロックを構成するパーツの数だけ繰り返す
            BlockSet -> Field : RefTransform            
            activate Field
                BlockSet <-- Field
            deactivate Field
        end
        BlockSet -> Field : SetBlocks
        activate Field
            BlockSet <-- Field
        deactivate Field
        alt ブロックが積みあがった
            BlockSet -> IPlayer : Dead()
            activate IPlayer
            deactivate IPlayer
        else
            BlockSet -> IPlayer : PullNextBlock
            activate IPlayer
                BlockSet <-- IPlayer 
            deactivate IPlayer
        end

    end
deactivate BlockSet
[<-- BlockSet

[-> BlockSet : NeedToFall
activate BlockSet
    BlockSet -> BlockSet : 落下待ちカウント(_countWaitFalling)を増やす
    activate BlockSet
    deactivate BlockSet
    opt 落下待ちカウント(_countWaitFalling)が上限に達した
        BlockSet -> BlockSet : 落下待ちカウント(_countWaitFalling)をリセット
        activate BlockSet
        deactivate BlockSet
        BlockSet -> BlockSet : 落下カウント(_countFalling)を増やす
        activate BlockSet
        deactivate BlockSet
        opt 落下カウント(_countFalling)が上限に達した or 落下中フラグ(_falling)がON
            BlockSet -> BlockSet : 落下中フラグ(_falling)をOFFにする
            activate BlockSet
            deactivate BlockSet
            BlockSet -> BlockSet : 落下カウント(_countFalling)をリセットする
            activate BlockSet
            deactivate BlockSet
            [<-- BlockSet : true
        end
    end
    [<-- BlockSet : false
deactivate BlockSet

[-> BlockSet : Setup
activate BlockSet
    BlockSet -> BlockSet : Field, BlockSet, IPlayer のインスタンスを保持する
    activate BlockSet
    deactivate BlockSet
    BlockSet -> BlockSet : 落下中フラグ(_falling)をOFFにする
    activate BlockSet
    deactivate BlockSet
    [<-- BlockSet
    BlockSet -> BlockSet : _activeBlocks を生成する
    activate BlockSet
        loop ブロックのパーツ毎に実行する
            BlockSet -> MonoBehaviour : Instantiate
            activate MonoBehaviour
                MonoBehaviour -> Block : create
                activate Block
                    MonoBehaviour <-- Block
                deactivate Block
                BlockSet <-- MonoBehaviour : _prefabPart を複製してブロックのパーツを構築する
            deactivate MonoBehaviour
        end
    deactivate BlockSet
    BlockSet -> Field : Width
    activate Field
        BlockSet <-- Field
    deactivate Field
    BlockSet -> BlockSet : ブロックの初期位置を決定する
    activate BlockSet
    deactivate BlockSet
    [<-- BlockSet
    
deactivate BlockSet

@enduml