@startuml


[-> StateGameMain : Setup
activate StateGameMain
    StateGameMain -> StateGameMain : プレイヤーの一覧を保持する
    activate StateGameMain
    deactivate StateGameMain
    [<-- StateGameMain
deactivate StateGameMain

Player -> StateGameMain : PlayerGameOver
activate StateGameMain
    StateGameMain -> StateGameMain : GetNumberOfAlivingPlayer
    activate StateGameMain
    deactivate StateGameMain
    opt 残りプレイヤーが一人になった
        StateGameMain -> GameController : FinishGame
        activate GameController
            StateGameMain <-- GameController
        deactivate GameController
    end
    Player <-- StateGameMain
deactivate StateGameMain

@enduml