@startuml

[-> Player : Setup
activate Player
    Player -> Player : 生存フラグを有効にする
    activate Player
    deactivate Player
    Player -> Player : ブロック群の選択肢を保持する
    activate Player
    deactivate Player
    Player -> MonoBehaviour : Instantiate
    activate MonoBehaviour
        MonoBehaviour -> AbstractField : create
        activate AbstractField
            MonoBehaviour <-- AbstractField
        deactivate AbstractField
        Player <-- MonoBehaviour : 生成されたAbstractField クラスのインスタンスを_currentBlock に保持する
    deactivate MonoBehaviour
    Player -> AbstractField : ResetField
    activate AbstractField
        Player <-- AbstractField
    deactivate AbstractField
    [<-- Player
deactivate Player

[-> Player : StartGame
activate Player
    Player -> Player : PullNextBlock
    activate Player
    deactivate Player
    [<-- Player
deactivate Player

[-> Player : IsAlive
activate Player
    [<-- Player : 生存フラグ
deactivate Player

[-> Player : BlockSetHasBeenPlaced
activate Player
    Player -> GameObject : Destroy
    activate GameObject
        GameObject -> BlockSet : GameObject を削除
        activate BlockSet
            GameObject <-- BlockSet
        deactivate BlockSet
        Player <-- GameObject
    deactivate GameObject
    [<-- Player
deactivate Player

[-> Player : PullNextBlock
activate Player
    Player -> Player : _blockSetOptions からブロックをランダムに選択する
    activate Player
    deactivate Player
    Player -> MonoBehaviour : Instantiate
    activate MonoBehaviour
        MonoBehaviour -> BlockSet : create
        activate BlockSet
            MonoBehaviour <-- BlockSet
        deactivate BlockSet
        Player <-- MonoBehaviour : 生成されたBlockSet クラスのインスタンスを_currentBlock に保持する
    deactivate MonoBehaviour
    Player -> BlockSet : Setup
    activate BlockSet
        Player <-- BlockSet
    deactivate BlockSet
    [<-- Player
deactivate Player

[-> Player : Dead()
activate Player
    Player -> Player : 生存フラグを無効にする
    activate Player
    deactivate Player
    Player -> StateGameMain : PlayerGameOver
    activate StateGameMain
        Player <-- StateGameMain
    deactivate StateGameMain
    [<-- Player
deactivate Player


@enduml