@startuml


[-> StateGameMain : Setup
activate StateGameMain
    StateGameMain -> StateGameMain : プレイヤーの一覧を保持する
    activate StateGameMain
    deactivate StateGameMain
    loop プレイヤーごとに実行
        StateGameMain -> Player : StartGame
        activate Player
        deactivate Player
    end
    [<-- StateGameMain
deactivate StateGameMain

[-> StateGameMain : PlayerGameOver
activate StateGameMain
    StateGameMain -> StateGameMain : GetNumberOfAlivingPlayer
    activate StateGameMain
    deactivate StateGameMain
    opt 残りプレイヤーが一人になった
        StateGameMain -> GameController : FinishGame
        activate GameController
            StateGameMain <-- GameController
        deactivate GameController
    end
    [<-- StateGameMain
deactivate StateGameMain

@enduml