behaviors:
  tetris2:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 120000
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
      # LSTM
      memory:
        sequence_length: 32
        memory_size: 128

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.96
        strength: 0.005
        encoding_size: 64
        learning_rate: 0.0003

      gail:
        gamma: 0.99
        strength: 0.005
        encoding_size: 64
        learning_rate: 0.0003
        use_actions: false
        use_vail: false
        demo_path: Tetris.demo

    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 1000
    summary_freq: 12000

#    behavioral_cloning:
#      demo_path: Tetris.demo
#      steps: 10000
#      strength: 0.5
#      samples_per_update: 0
