name: doxygen - PlantUML
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_doxygen_and_plantuml:
    name: doxygen_plantuml
    runs-on: ubuntu-latest
    env:
        UML_FILES: "*.pu"
        UML_FILES_GENERATED: "*.puml"
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Get Python version
      run: python -V
    - name: Install dependencies
      run: pip install -r python/requirements.txt
    - name: Get changed UML files
      id: getfile
      run: |
        echo "::set-output name=files::$(find ./Documents/PlantUML -not -path ./Documents/PlantUML/mindmap/* -name ${{ env.UML_FILES }} -o -name ${{ env.UML_FILES_GENERATED }} | xargs)"
    - name: UML files considered echo output
      run: |
        echo ${{ steps.getfile.outputs.files }}
    - name: Generate SVG Diagrams
      uses: cloudbees/plantuml-github-action@master
      with:
          args: -charset UTF-8 -tsvg ${{ steps.getfile.outputs.files }}
    - name: doxygen
      uses: mattnotmitt/doxygen-action@v1
      with:
        working-directory: ./
        doxyfile-path: ./Documents/Doxygen/Doxyfile
    - name: show list of .svg which are generated just now
      run: |
        find ./Documents/PlantUML -name *.svg
    - name: create index of PlantUML # This step must run after svgs are genearted. 
      run: |
        python ./python/index_generator.py ./Documents/PlantUML ./Documents/PlantUML ./PlantUML > ./Documents/public/index.html
    - name: copy svg for PlantUML into public
      run: |
        mkdir -p ./Documents/public/PlantUML
        find  ./Documents/PlantUML -name *.svg | xargs mv -t ./Documents/public/PlantUML/
        find  ./Documents/PlantUML -name *.html | xargs mv -t ./Documents/public/PlantUML/
    - name: convert .md to .html in public
      run: |
        pip3 install markdown
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Documents/public
