name: doxygen - PlantUML
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_doxygen_and_plantuml:
    name: doxygen_plantuml
    runs-on: ubuntu-latest
    env:
        UML_FILES: "*.pu"
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Get changed UML files
      id: getfile
      run: |
        echo "::set-output name=files::$(find ./Documents/PlantUML -name ${{ env.UML_FILES }} | xargs)"
    - name: UML files considered echo output
      run: |
        echo ${{ steps.getfile.outputs.files }}
    - name: Generate SVG Diagrams
      uses: cloudbees/plantuml-github-action@master
      with:
          args: -charset UTF-8 -tsvg ${{ steps.getfile.outputs.files }}
    - name: doxygen
      uses: mattnotmitt/doxygen-action@v1
      with:
        working-directory: ./
        doxyfile-path: ./Documents/Doxygen/Doxyfile
    - name: show list of .svg which are generated just now
      run: |
        ls ./Documents/PlantUML/*.svg
    - name: copy svg for PlantUML into public
      run: |
        mkdir -p ./Documents/public/plant_uml
        mv ./Documents/PlantUML/*.svg ./Documents/public/plant_uml/
    - name: convert .md to .html in public
      run: |
        pip3 install markdown
        python3 ./Script/md2html.py ./Documents/Planning/Readme.md ./Documents/public/concept.html ./Script/template.html ./Script/template_menu.html
        python3 ./Script/source2html.py ./Script/html_source/index.html ./Documents/public/index.html ./Script/template.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Documents/public
